TMWDaily/config/routes.rb
TMWDaily::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:sessions => 'devise:sessions'}, :skip => [:sessions] do
    get 'login'   => 'devise/sessions#new',         :as => :new_user_session         
    post 'login'  => 'devise/sessions#create',      :as => :user_session          
    get 'logout'  => 'devise/sessions#destroy',     :as => :destroy_user_sessions
    get 'signup'  => 'devise/registrations#new',    :as => :new_user_account
    post 'signup' => 'devise/registrations#create', :as => :user_account
  end


  #devise_for :users do
  #  get "/login"  => "devise/sessions#new"
  #  get "/logout" => "devise/sessions#destroy"
  #end

  match "/" => "headlines#create", :via => :post, :as => :new_index_headline
  scope "me" do
    match "headlines" => "headlines#me_index", :via => :get, :as => :me_headlines
    match "current" => "headlines#me_current_show", :via => :get, :as => :me_current
  end
  scope "eveningstandard" do
    match "headlines" => "headlines#evening_index", :via => :get, :as => :devine_headlines
    match "headline/:id" => "headlines#evening_show", :via => :get, :as => :devine_headline
  end
  match "user/:id/headlines" => "headlines#index", :via => :get, :as => :user_headlines
  match "headline/:id" => "headlines#show", :via => :get, :as => :headline

  root :to => "Headlines#new"


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

TMWDaily/app/models/headline.rb
class Headline < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags

	validates :user_id, :presence =>true
	validates :name, :presence => true
	validate :user_cant_save_multiples_headline_a_day, :on => :create

	scope :current, lambda { where("created_at >= ?", Headline.get_start_date) }
	scope :history, lambda { where("created_at < ?", Headline.get_start_date).order("created_at DESC") }

	after_create :create_tags_from_new_headline

	def user_cant_save_multiples_headline_a_day
		if self.user
			unless self.user.headlines.current.empty?
				errors.add :name, "User can't print two headline for the same issue"
			end
		end
	end

	def self.get_start_date
		startDate = DateTime.current.change :hour => 18
		if DateTime.now.hour < 18
			startDate = startDate - 1.day
		end
		return startDate
	end

	def self.get_random_current_headlines(n)
		Headline.current.order("random()").limit(n)
	end

	def extract_tags
		tags = self.name.split.delete_if { |item| item.size < 3 }
	end

	def get_statistics
		tag_count = Tag.current.sum("count").to_f
		average_length = (Headline.current.map { |h| h.tags.count }).inject { |sum,t| sum + t} / Headline.current.count
		return {:tag_count => tag_count, :average_length => average_length}
	end

	def to_param
		"#{id}-#{name.parameterize}"
	end

	###########
	# SCORING #
	###########

	def set_score
		set_score_by_tags
		set_score_by_headline_length
	end

	def set_score_by_tags
		tags.each do |tag|
			tag.headlines.each do |headline|
				if headline.user.type == 'User'
					headline.score += tag.name.length
					headline.save!
				end
			end
		end
	end

	def set_score_by_headline_length
		devine_tags_count = tags.count
		Headline.current.each do |headline|
			if headline.user.type == 'User'
				tags_count = headline.tags.count
				total = 3 - (devine_tags_count - tags_count).abs
				headline.score += total >= 0 ? total : 0
				headline.save!
			end
		end
	end

	private
		def create_tags_from_new_headline
			self.extract_tags.map{|item| item.capitalize}.each do |tag|
				resultTag = Tag.current.find_by_name(tag)
				if resultTag.nil? then
					  t = self.tags.create :name => tag, :count => 0
					  t.increment(:count) if self.user.type == 'User'
					  t.save
				else
					resultTag.increment(:count) if self.user.type == "User"
					resultTag.save
					self.tags << resultTag
				end
			end
		end

end

TMWDaily/app/controllers/headlines_controller.rb
require 'open-uri'

class HeadlinesController < ApplicationController

	before_filter :authenticate_user!, :except => [:new, :index, :show, :evening_index]


	# GET /
	# GET /headlines
	def new
		@headline = Headline.new
		retrieve_index_infos
	end

	# POST /
	# POST /headlines
	def create
		@headline = current_user.headlines.build params[:headline]
		retrieve_index_infos
		if @headline.save then
			flash[:notice] = "Headline saved"
			redirect_to me_headlines_path
		else
			render :action => "new"
		end
	end

	# GET /user/:id/headlines
	def index
		@user = User.find(params[:id])

		redirect_to devine_headlines_path if @user.type == "DevineUser"

		@headlines = @user.headlines.order("created_at DESC")
		current = @headlines.select { |h| h.created_at >= Headline.get_start_date }
		unless current.empty?
			@current_headline = current.first
			@headlines = @headlines.delete_if { |h| h.created_at >= Headline.get_start_date}
		end
	end

	# GET /headlines/:id
	def show
		@headline = Headline.history.find(params[:id])
	end

	# GET /me/headlines
	def me_index
		@headlines = current_user.headlines.order("created_at DESC")
		current = @headlines.select { |h| h.created_at >= Headline.get_start_date }
		unless current.empty?
			@current_headline = current.first
			@headlines = @headlines.delete_if { |h| h.created_at >= Headline.get_start_date}
		end
		render :action => "index"
	end

	# GET /me/current
	def me_current_show
		if @current_headline = current_user.headlines.current.first then
			@statistics = @current_headline.get_statistics
		else
			redirect_to "/me/headlines"
		end
	end

	#GET /eveningstandard/headlines
	def evening_index
		devine = DevineUser.first
		@headlines = devine.headlines.order("created_at DESC")
	end

	#GET /eveningstandard/headline/:id
	def evening_show
		@headline = DevineUser.first.headlines.find(params[:id])
	end


	####
	#Functions
	####

	def retrieve_index_infos
		@last_devine_headlines = DevineUser.first.get_last_headlines(10)
		@twitter_trends = get_twitter_trends(44418)
		#@twitter_trends = ["Twitt1", "Twitt2", "Twitt3", "Twitt4", "Twitt5"]
	end

	def get_twitter_trends(woid)
		buffer = open("https://api.twitter.com/1/trends/#{woid}.json")
		if buffer.status.first == 420 then
			raise 'Twitter Rate Limite'
		end
		twitter = JSON.parse(buffer.read)
		return twitter[0]['trends']
	end


end

TMWDaily/app/helpers/headlines_helper.rb
module HeadlinesHelper
	
end

TMWDaily/app/views/headlines/_current_headline.html.erb
<div class="hero-unit">
	<p>Your next issue headline :</p>
	<h1><%= link_to @current_headline.name, me_current_path %></h1>
</div>

TMWDaily/app/views/headlines/_inspiration.html.erb
<div class="page-header">
	<h1>Need Inspiration ?</h2>
</div>

<div class="row">
	<div class="span6">
		<h2>Last issue's headlines <small>London</small> </h2>
		<table class="table">
			<% @last_devine_headlines.each do |headline| %>
				<tr>
					<td><%= link_to headline.name, devine_headline_path(headline) %></td>
					<td><%= headline.created_at.to_formatted_s(:rfc822) %></td>
				</tr>
			<% end %>
		</table>
		<%= link_to "view all", devine_headlines_path, :class => "right" %>
	</div>
	<div class="span6">
		<h2>Twitter Trends <small>London</small> </h2>
		<table class="table">
			<% @twitter_trends.each do |twit| %>
				<tr>
					<td><%= link_to twit['name'], twit['url'] %></td>
				</tr>
			<% end %>	
		</table> 
	</div>
</div>

TMWDaily/app/views/headlines/evening_index.html.erb
<div class="page-header">
	<h1>Last issue's headlines</h1>
</div>

<div class="row">
	<div class="span6">
		<table class="table">
			<thead>
				<tr>
					<th>name</th>
					<th>date</th>
				</tr>
			</thead>
			<% @headlines.each do |headline| %>
				<tr>
					<td><%= link_to headline.name, devine_headline_path(headline) %></td>
					<td><%= headline.created_at.to_formatted_s(:rfc822) %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

TMWDaily/app/views/headlines/evening_show.html.erb
<%= @headline.name %>

TMWDaily/app/views/headlines/index.html.erb
<% if @current_headline then %>
	<%= render "current_headline" %>
<% end %>

<h2>Previous Headlines</h2>
<table class="table table-striped">
	<% @headlines.each do |headline| %>
		<tr>
			<td><%= link_to headline.name, headline_path(headline) %></td>
			<td><%= link_to headline.created_at, "#" %></td>
			<td></td>
		</tr>
	<% end %>
</div>

TMWDaily/app/views/headlines/me_current_show.html.erb
<div class="hero-unit">
	<h1><%= @current_headline.name %></h1>
</div>

<h2>Tags</h2>
<table class="table">
	<thead>
		<tr>
			<th>name</th>
			<th>%</th>
		</tr>
	</thead>
	<% tags = @current_headline.tags.order("count DESC").each do |tag| %>
		<tr>
			<td><%= tag.name %></td>
			<td><%= (tag.count / @statistics[:tag_count] * 100).round(2) %>%</td>
		</tr>
	<% end %>
	<tr>
		<th>Total</th>
		<% sum = 0 %>
		<th><%= ((tags.map(&:count).inject { |sum, t| sum + t}) / @statistics[:tag_count] *100).round(0) %>%</th>
	</tr>
</table>

<h2>Average</h2>
<h3>Your length <%= tags.count %> <small>average lenght <%= @statistics[:average_length] %></small></h3>

TMWDaily/app/views/headlines/new.html.erb
<header class="hero-unit">
	<h1>Guess Evening Standard Headline</h1>
	<p>Be the first to guess evening standard next issue's headline</p>

	<%= simple_form_for @headline, :url => new_index_headline_path, :wrapper => :default, :html => {:id => "print-headline", :class => "form-inline"} do |f| %>
		<%= f.input :name, :required => false, :label => false, :wrapper => false, :input_html => {:class => "span6"} %>
		<%= f.button :submit, "Print it", :class => "btn-primary" %>
	<% end %>
</header>

<%= render "inspiration" %>

TMWDaily/app/views/headlines/show.html.erb
<%= @headline.name %>

TMWDaily/app/views/headlines/show_current.html.erb
<div class="hero-unit">
	<h1><%= @current_headline.name %></h1>
</div>

<h2>Tags</h2>
<table class="table">
	<thead>
		<tr>
			<th>name</th>
			<th>%</th>
		</tr>
	</thead>
	<% tags = @current_headline.tags.order("count DESC").each do |tag| %>
		<tr>
			<td><%= tag.name %></td>
			<td><%= (tag.count / @statistics[:tag_count] * 100).round(2) %>%</td>
		</tr>
	<% end %>
	<tr>
		<th>Total</th>
		<% sum = 0 %>
		<th><%= ((tags.map(&:count).inject { |sum, t| sum + t}) / @statistics[:tag_count] *100).round(0) %>%</th>
	</tr>
</table>

<h2>Average</h2>
<h3>Your length <%= tags.count %> <small>average lenght <%= @statistics[:average_length] %></small></h3>