TMWDaily/config/routes.rb
TMWDaily::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:sessions => 'devise:sessions'}, :skip => [:sessions] do
    get 'login'   => 'devise/sessions#new',         :as => :new_user_session         
    post 'login'  => 'devise/sessions#create',      :as => :user_session          
    get 'logout'  => 'devise/sessions#destroy',     :as => :destroy_user_sessions
    get 'signup'  => 'devise/registrations#new',    :as => :new_user_account
    post 'signup' => 'devise/registrations#create', :as => :user_account
  end


  #devise_for :users do
  #  get "/login"  => "devise/sessions#new"
  #  get "/logout" => "devise/sessions#destroy"
  #end

  match "/" => "headlines#create", :via => :post, :as => :new_index_headline
  scope "me" do
    match "headlines" => "headlines#me_index", :via => :get, :as => :me_headlines
    match "current" => "headlines#me_current_show", :via => :get, :as => :me_current
  end
  scope "eveningstandard" do
    match "headlines" => "headlines#evening_index", :via => :get, :as => :devine_headlines
    match "headline/:id" => "headlines#evening_show", :via => :get, :as => :devine_headline
  end
  match "user/:id/headlines" => "headlines#index", :via => :get, :as => :user_headlines
  match "headline/:id" => "headlines#show", :via => :get, :as => :headline

  root :to => "Headlines#new"


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

TMWDaily/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TMWDaily</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<ul class="nav">
				<li class="active"><%= nav_to "Home", root_path %></li>
				<li><%= nav_to "My Headlines", me_headlines_path %></li>
				<li class="divider-vertical"></li>
			</ul>
			<ul class="nav pull-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">My profile <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<% if user_signed_in? then %>
								<li><a href="#">Account Detail</a></li>
								<li><%= nav_to "Logout", destroy_user_sessions_path %></li>
							<% else %>
								<li><%= nav_to "Sign Up", new_user_account_path %></li>
								<li><%= nav_to "Login",  new_user_session_path %></li>
							<% end %>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<% if flash[:notice] %>
		<div class="alert alert-notice">
			<a class="close" data-dismiss="alert">×</a>
			<%= flash[:notice] %>
		</div>
	<% end %>
	<%= yield %>
</div>

</body>
</html>